Grob.ServiceFabric/Grob.ServiceFabric.Web/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Grob.Docker;
using Grob.Entities.Grob;
using Grob.Master.Models;
using Grob.ServiceFabric.Web.Models.Applications;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;

namespace Grob.ServiceFabric.Web.Controllers
{
    public class ApplicationsController : Controller
    {
        private IGrobMasterService _grobMasterService;
        private DockerManager _dockerManager;

        public ApplicationsController()
        {
            _grobMasterService = ServiceProxy.Create<IGrobMasterService>(new Uri("fabric:/Grob.ServiceFabric/Grob.ServiceFabric.Master"), new ServicePartitionKey(1));
            _dockerManager = new DockerManager();
        }

        // GET: Applications
        public async Task<ActionResult> Index()
        {
            var model = new ApplicationsIndexModel()
            {
                Applications = await _grobMasterService.GetApplicationsAsync()
            };

            return View(model);
        }

        // GET: Applications/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            var model = new NewApplicationViewModel();
            
            var applicationTypes = Enum.GetValues(typeof(ApplicationTypeEnum)).Cast<ApplicationTypeEnum>().ToList();

            applicationTypes.ForEach(type => model.ApplicationTypes.Add(new SelectListItem()
            {
                Value = type.ToString(),
                Text = type.ToString()
            }));

            return View(model);
        }

        // POST: Applications/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(NewApplicationViewModel model)
        {
            var guid = Guid.NewGuid();
            string archiveName = $"{model.Name}.zip";
            string containerPath = $"Archives/{guid}";

            try
            {
                string archivePath = $"{containerPath}/{archiveName}";
                string extractPath = $"{containerPath}/extractionFoler";
                Directory.CreateDirectory(containerPath);

                using (var fileStream = new FileStream(archivePath, FileMode.CreateNew))
                {
                    model.Archive.CopyTo(fileStream);
                }

                ZipFile.ExtractToDirectory(archivePath, extractPath);

                CreateDockerFile(extractPath, model.Name, model.ApplicationType);
                await _dockerManager.CreateImageAsync($"{Directory.GetCurrentDirectory()}/{extractPath}", model.Name.ToLower());

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return View();
            }
            finally
            {
                Directory.Delete(containerPath, true);
            }
        }

        private void CreateDockerFile(string extractionPath, string entryPointFile, ApplicationTypeEnum applicationType)
        {
            var dockerFilePath = $"{extractionPath}/Dockerfile";

            //System.IO.File.Create(dockerFilePath);
            var content = new StringBuilder();

            switch (applicationType)
            {
                case ApplicationTypeEnum.DotnetFramework:
                    content.AppendLine("FROM microsoft/windowsservercore");
                    content.AppendLine("ADD . grobPackage");
                    content.AppendLine($"ENTRYPOINT [\"C:\\\\grobPackage\\\\{entryPointFile}.exe\"]");
                    break;
                case ApplicationTypeEnum.AspNetCore:
                    content.AppendLine("FROM microsoft/aspnetcore");
                    content.AppendLine("ADD . grobPackage");
                    content.AppendLine("WORKDIR /grobPackage");
                    content.AppendLine($"ENTRYPOINT [\"dotnet\", \"{entryPointFile}.dll\"]");
                    break;
            }
            

            using (var streamWriter = new StreamWriter(dockerFilePath))
            {
                streamWriter.Write(content.ToString());
            }
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Applications/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Applications/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Grob.ServiceFabric/Grob.ServiceFabric.Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Grob.Entities.Grob;
using Grob.Master.Models;
using Grob.Scheduler.Models;
using Grob.ServiceFabric.Web.Models;
using Grob.ServiceFabric.Web.Models.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;

namespace Grob.ServiceFabric.Web.Controllers
{
    public class TaskController : Controller
    {        
        private IGrobSchedulerService _grobSchedulerService;
        private IGrobMasterService _grobMasterService;

        public TaskController()
        {            
            _grobSchedulerService = ServiceProxy.Create<IGrobSchedulerService>(new Uri("fabric:/Grob.ServiceFabric/Grob.ServiceFabric.Scheduler"), new ServicePartitionKey(1));
            _grobMasterService = ServiceProxy.Create<IGrobMasterService>(new Uri("fabric:/Grob.ServiceFabric/Grob.ServiceFabric.Master"), new ServicePartitionKey(1));
        }

        // GET: Task
        public IActionResult Index()
        {
            var model = new TaskViewModel
            {
                Tasks = _grobSchedulerService.GetTasksAsync().Result.OrderBy(t => t.CreationTime).ToList()
            };

            return View("Index", model);
        }
        
        [Route("task/{taskName}"),HttpGet]
        public async Task<IActionResult> Details([FromRoute]string taskName)
        {
            var model = new TaskDetailsModel()
            {
                GrobTask = await _grobSchedulerService.GetTaskAsync(taskName)
            };

            return View("TaskDetails", model);
        }

        [Route("task/create"), HttpGet]
        // GET: Task/Create
        public IActionResult Create()
        {
            var model = new NewTaskModel();

            var applications = _grobMasterService.GetApplicationsAsync().Result;
            applications.ForEach(a => model.RegisteredApplications.Add(new SelectListItem()
            {
                Text = a.Name,
                Value = a.Name
            }));

            var scheduleTypes = Enum.GetValues(typeof(ScheduleTypesEnum)).Cast<ScheduleTypesEnum>().ToList();
            scheduleTypes.ForEach(s => model.ScheduleTypes.Add(new SelectListItem()
            {
                Text = s.ToString(),
                Value = s.ToString()
            }));

            var containerTypes = Enum.GetValues(typeof(ContainerTypeEnum)).Cast<ContainerTypeEnum>().ToList();
            containerTypes.ForEach(c => model.ContainerTypes.Add(new SelectListItem()
            {
                Text = c.ToString(),
                Value = c.ToString()
            }));

            return View(model);
        }

        // POST: Task/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(NewTaskModel newTaskModel)
        {
            try
            {                
                var task = new GrobTask(newTaskModel.TaskName, newTaskModel.ApplicationName, newTaskModel.ScheduleType, newTaskModel.ScheduleInfo, newTaskModel.ContainerType, newTaskModel.RequiredMemory);
                task = await _grobMasterService.CreateContainerForTaskAsync(task);
                await _grobSchedulerService.CreateTaskAsync(task);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View();
            }
        }

        // POST: Task/Delete/5
        [Route("/delete/{taskId}"), HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid taskId)
        {
            try
            {
                await _grobSchedulerService.DeleteTaskAsync(taskId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Grob.ServiceFabric/Grob.ServiceFabric.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/materialize.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Grob</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Task" asp-action="Index">Tasks</a></li>
                    <li><a asp-area="" asp-controller="Containers" asp-action="Index">Containers</a></li>
                    <li><a asp-area="" asp-controller="Applications" asp-action="Index">Applications</a></li>
                </ul>
            </div>
        </div>
    </nav>*@
    <nav class="nav-wrapper navbar-fixed-top blue lighten-1">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="brand-logo">Grob</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="right hide-on-med-and-down">
                    <li><a asp-area="" asp-controller="Task" asp-action="Index">Tasks</a></li>
                    <li><a asp-area="" asp-controller="Containers" asp-action="Index">Containers</a></li>
                    <li><a asp-area="" asp-controller="Applications" asp-action="Index">Applications</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Grob.ServiceFabric.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/materialize.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>